# Generated by Django 4.2.7 on 2024-01-30 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('day4app', '0003_alter_course_course_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('std_id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('std_name', models.CharField(max_length=50)),
                ('std_enrolled_courses', models.ManyToManyField(to='day4app.course')),
            ],
        ),
    ]
