# Generated by Django 4.2.7 on 2024-01-30 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('day4app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='course_type',
            field=models.CharField(choices=[('theory', 'Theory'), ('lab', 'Lab'), ('project', 'Project')], default='theory', max_length=10),
        ),
    ]
